"""Spec-driven plumbing codegen for a new glossary term (bead MetaCoding-b5r).

MetaCoding-yph measured the cost of one new fixture-vocabulary term: an 8–9
file change (glossary set, probe/operation contract, adapter ABC, farmOS
adapter, port surface, runner dispatch, flowspec validation, tests), and 14 of
the first 25 terms arrived from just two features. This module generates that
plumbing from one TERM-SPEC v1, so the marginal cost of a term is a review of
one diff, not an archaeology of nine files.

What it generates, by kind (all as text edits against a TARGET TREE — the
``--root`` a caller names, never implicitly this repo):

* every kind — the glossary set entry, and a test skeleton that pins the term's
  registration and its loud-failure behaviour;
* ``assertion`` — a :class:`ProbeSpec` in ``probes._PROBES`` declared
  ``authority=DERIVED`` with the spec's probe semantics as the derivation and
  **no** ``validated_against``: honest by construction, its values cannot score
  until someone validates the derivation (``is_evidence`` is False), and the
  provenance row keeps it PROVISIONAL besides; adapter stubs on the ABC and the
  farmOS adapter;
* ``action`` — an :class:`OperationSpec` in ``probes._OPERATIONS``, the
  interpreter arm in ``steps.apply_when``, and the same adapter stubs.

**The fake-green rule, structurally.** Every generated adapter stub RAISES
(``AdapterError`` on the ABC, ``NotImplementedError`` on the farmOS adapter,
each carrying the spec's probe semantics) — a stub that returned a constant
would be a port that answers questions nobody implemented, which is the exact
defect the probe contract exists to make impossible.

Anchors are matched exactly and FAIL LOUDLY (:class:`CodegenError`) when the
target tree has drifted: a misplaced insertion is worse than none.
"""

from __future__ import annotations

import difflib
import json
from dataclasses import dataclass
from pathlib import Path

from ctkr.oracle.glossary_provenance import validate_term_spec

GLOSSARY = "ctkr/oracle/glossary.py"
PROBES = "ctkr/oracle/probes.py"
STEPS = "ctkr/oracle/steps.py"
ADAPTER = "ctkr/oracle/adapter.py"
FARMOS = "ctkr/oracle/farmos_adapter.py"

_SET_FOR_KIND = {
    "entity": "ENTITY_TERMS",
    "action": "ACTION_TERMS",
    "assertion": "ASSERTION_TERMS",
}


class CodegenError(RuntimeError):
    """The spec is invalid or the target tree does not match the anchors."""


@dataclass(frozen=True)
class FileEdit:
    """One file's before/after under the target root. ``before == ""`` = new file."""

    rel_path: str
    before: str
    after: str

    @property
    def is_new(self) -> bool:
        return self.before == ""


def _read(root: Path, rel: str) -> str:
    p = root / rel
    if not p.is_file():
        raise CodegenError(f"target tree {root} has no {rel} — wrong --root?")
    return p.read_text(encoding="utf-8")


def _insert_before(source: str, anchor: str, text: str, rel: str) -> str:
    idx = source.find(anchor)
    if idx < 0:
        raise CodegenError(
            f"{rel}: anchor {anchor.splitlines()[0]!r}... not found — the "
            f"target tree has drifted from what this generator knows; refusing "
            f"to guess an insertion point"
        )
    if source.find(anchor, idx + 1) >= 0:
        raise CodegenError(f"{rel}: anchor is ambiguous ({anchor[:40]!r} twice)")
    return source[:idx] + text + source[idx:]


def _short(text: str, limit: int = 68) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1] + "…"


# --------------------------------------------------------------------------- #
# Per-file generators                                                          #
# --------------------------------------------------------------------------- #
def _glossary_edit(src: str, term: str, kind: str, description: str) -> str:
    if f'"{term}"' in src:
        raise CodegenError(f"term {term!r} is already in the glossary")
    set_name = _SET_FOR_KIND[kind]
    marker = f"{set_name}: frozenset[str] = frozenset("
    start = src.find(marker)
    if start < 0:
        raise CodegenError(f"{GLOSSARY}: cannot find the {set_name} set")
    close = src.find("\n    }", start)
    if close < 0:
        raise CodegenError(f"{GLOSSARY}: cannot find the end of {set_name}")
    line = f'\n        "{term}",  # {_short(description)} [PROVISIONAL]'
    return src[:close] + line + src[close:]


def _probe_entry(term: str, description: str, probe_semantics: str) -> str:
    return (
        f"    # --- generated by `ctkr add-term` (PROVISIONAL until bind-term) ----- #\n"
        f"    # DERIVED with no validated_against ON PURPOSE: the derivation below is\n"
        f"    # the spec's proposed semantics, which no source authority has validated\n"
        f"    # yet — so is_evidence is False and values cannot score until it is.\n"
        f'    ProbeSpec({term!r}, {term!r}, (),\n'
        f"              doc={_short(description, 160)!r},\n"
        f"              authority=DERIVED,\n"
        f"              derivation={_short(probe_semantics, 240)!r}),\n"
    )


def _operation_entry(term: str, description: str) -> str:
    return (
        f"    # generated by `ctkr add-term` (PROVISIONAL until bind-term)\n"
        f"    OperationSpec({term!r}, ({term!r},),\n"
        f"                  doc={_short(description, 160)!r}),\n"
    )


def _steps_arm(term: str) -> str:
    return (
        f'    elif w.action == "{term}":\n'
        f"        # generated by `ctkr add-term` — review the argument mapping when\n"
        f"        # implementing the adapter; the default adapter method RAISES, so\n"
        f"        # this arm cannot fake a recorded flow before that happens.\n"
        f"        adapter.{term}(handles[w.ref])\n"
    )


def _adapter_stub(term: str, kind: str, probe_semantics: str) -> str:
    return (
        f"\n    # --- generated: {term} ({kind}, PROVISIONAL) --- #\n"
        f"    def {term}(self, subject_handle: Handle) -> Any:\n"
        f'        """{_short(probe_semantics, 300)}\n'
        f"\n"
        f"        Generated stub — raises until an implementation exists. A stub\n"
        f"        that returned a constant could be mistaken for an observed value.\n"
        f'        """\n'
        f'        raise self._unsupported("{term}")\n'
    )


def _farmos_stub(term: str, kind: str, probe_semantics: str) -> str:
    return (
        f"    # --- generated: {term} ({kind}, PROVISIONAL) --- #\n"
        f"    def {term}(self, subject_handle: Handle) -> Any:\n"
        f'        """{_short(probe_semantics, 300)}\n'
        f"\n"
        f"        Generated stub: implement against the live boundary, then record\n"
        f"        and `ctkr bind-term {term}`. Raises so an unimplemented probe can\n"
        f"        never be mistaken for an observed value.\n"
        f'        """\n'
        f"        raise NotImplementedError(\n"
        f"            {(_short(probe_semantics, 200) + ' — ' + term + ' is PROVISIONAL and unimplemented')!r}\n"
        f"        )\n\n"
    )


def _test_skeleton(term: str, kind: str, spec: dict) -> str:
    flow = json.dumps(spec["discriminating_flow"], indent=2, sort_keys=True)
    lines = [
        f'"""Generated by `ctkr add-term` for PROVISIONAL {kind} term {term!r}.',
        "",
        "Pins what the plumbing guarantees BEFORE any implementation exists:",
        "the term is registered, the contract has no holes, and nothing can",
        "fake an answer for it. Replace the discriminating flow below with a",
        "recorded fixture once the term is bound.",
        '"""',
        "",
        "import json",
        "",
        "import pytest",
        "",
        "from ctkr.oracle import glossary",
        "from ctkr.oracle.probes import contract_gaps",
        "",
        f"TERM = {term!r}",
        "",
        "# The spec's discriminating flow — the scenario a recording must exercise",
        "# for `ctkr bind-term` to flip this term provisional -> bound.",
        f"DISCRIMINATING_FLOW = json.loads(r'''{flow}''')",
        "",
        "",
        f"def test_{term}_is_a_registered_glossary_term() -> None:",
        "    assert TERM in glossary.all_terms()",
        "    assert contract_gaps() == []",
        "",
    ]
    if kind in ("action", "assertion"):
        lines += [
            "",
            f"def test_{term}_unimplemented_stub_fails_loudly() -> None:",
            '    """The fake-green rule: an unimplemented surface RAISES, never answers."""',
            "    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter",
            "",
            "    bare = type('_Bare', (ImplementationAdapter,), {})",
            "    bare.__abstractmethods__ = frozenset()",
            "    with pytest.raises(AdapterError):",
            "        getattr(bare(), TERM)('H')",
            "",
        ]
    if kind == "assertion":
        lines += [
            "",
            f"def test_{term}_is_not_yet_evidence() -> None:",
            '    """PROVISIONAL: derived, unvalidated — its values cannot score."""',
            "    from ctkr.oracle.probes import PROBE_CONTRACT",
            "",
            "    assert not PROBE_CONTRACT[TERM].is_evidence",
            "",
        ]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Plan / render / apply                                                        #
# --------------------------------------------------------------------------- #
def plan_edits(spec: dict, root: str | Path) -> list[FileEdit]:
    """Every file edit the term needs, computed against the tree at ``root``.

    ``root`` is the directory that CONTAINS the ``ctkr`` package (and
    ``tests/``). Nothing is written; :func:`apply_edits` does that.
    """
    problems = validate_term_spec(spec)
    if problems:
        raise CodegenError("not a TERM-SPEC v1:\n  - " + "\n  - ".join(problems))
    root = Path(root)
    term, kind = spec["term"], spec["kind"]
    description, semantics = spec["description"], spec["probe_semantics"]

    edits: list[FileEdit] = []

    g = _read(root, GLOSSARY)
    edits.append(FileEdit(GLOSSARY, g, _glossary_edit(g, term, kind, description)))

    if kind == "assertion":
        p = _read(root, PROBES)
        p2 = _insert_before(p, "\n)\n\nPROBE_CONTRACT",
                            "\n" + _probe_entry(term, description, semantics).rstrip("\n"),
                            PROBES)
        edits.append(FileEdit(PROBES, p, p2))
    elif kind == "action":
        p = _read(root, PROBES)
        p2 = _insert_before(p, "\n)\n\nOPERATION_CONTRACT",
                            "\n" + _operation_entry(term, description).rstrip("\n"),
                            PROBES)
        edits.append(FileEdit(PROBES, p, p2))
        s = _read(root, STEPS)
        s2 = _insert_before(s, "    else:\n        raise AdapterError",
                            _steps_arm(term), STEPS)
        edits.append(FileEdit(STEPS, s, s2))

    if kind in ("action", "assertion"):
        a = _read(root, ADAPTER)
        if f"def {term}(" in a:
            raise CodegenError(f"{ADAPTER}: method {term!r} already exists")
        edits.append(FileEdit(ADAPTER, a, a.rstrip("\n") + "\n" + _adapter_stub(term, kind, semantics)))

        f = _read(root, FARMOS)
        if f"def {term}(" in f:
            raise CodegenError(f"{FARMOS}: method {term!r} already exists")
        f2 = _insert_before(f, "\ndef _iso(", "\n" + _farmos_stub(term, kind, semantics), FARMOS)
        edits.append(FileEdit(FARMOS, f, f2))

    test_rel = f"tests/test_term_{term}.py"
    if (root / test_rel).exists():
        raise CodegenError(f"{test_rel} already exists")
    edits.append(FileEdit(test_rel, "", _test_skeleton(term, kind, spec)))
    return edits


def render_diffs(edits: list[FileEdit]) -> str:
    """The full unified diff a --dry-run prints."""
    out: list[str] = []
    for e in edits:
        out.extend(
            difflib.unified_diff(
                e.before.splitlines(keepends=True),
                e.after.splitlines(keepends=True),
                fromfile=f"a/{e.rel_path}" if not e.is_new else "/dev/null",
                tofile=f"b/{e.rel_path}",
            )
        )
        if out and not out[-1].endswith("\n"):
            out[-1] += "\n"
    return "".join(out)


def apply_edits(edits: list[FileEdit], root: str | Path) -> list[Path]:
    """Write every edit under ``root``; refuses if any file moved since planning."""
    root = Path(root)
    for e in edits:  # verify the WHOLE plan before touching anything
        p = root / e.rel_path
        current = p.read_text(encoding="utf-8") if p.exists() else ""
        if current != e.before:
            raise CodegenError(
                f"{e.rel_path} changed between planning and applying — re-plan"
            )
    written: list[Path] = []
    for e in edits:
        p = root / e.rel_path
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(e.after, encoding="utf-8")
        written.append(p)
    return written
