"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'is_sterile'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'is_sterile'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "STERILE",
      "entity": "animal",
      "is_sterile": true,
      "name": "Steer"
    },
    {
      "alias": "FERTILE",
      "entity": "animal",
      "is_sterile": false,
      "name": "Bull"
    },
    {
      "alias": "UNSAID",
      "entity": "animal",
      "name": "Calf"
    }
  ],
  "key": "lin-sterility-is-three-answers",
  "probes": [
    {
      "assert": "is_sterile",
      "subject": "STERILE"
    },
    {
      "assert": "is_sterile",
      "subject": "FERTILE"
    },
    {
      "assert": "is_sterile",
      "subject": "UNSAID"
    }
  ],
  "title": "Recorded sterile, recorded fertile, and never said are three different answers",
  "when": []
}''')


def test_is_sterile_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_is_sterile_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_is_sterile_authority_was_refined_before_the_first_recording() -> None:
    """AUTHORITY REFINED post-generation (MetaCoding-b0s): BOUNDARY — a real tri-state the source states directly on the asset; unstated, true and false are three answers.

    Inverted rather than deleted, per the e6p lesson: a BOUND term whose
    ProbeSpec cannot score is a skipped refinement, and it is silent.
    """
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert PROBE_CONTRACT[TERM].is_evidence, PROBE_CONTRACT[TERM].unvalidated_reason
