"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'is_fixed'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'is_fixed'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "BARN",
      "entity": "structure",
      "intrinsic_geometry": "POINT (1 2)",
      "is_fixed": true,
      "name": "Barn"
    },
    {
      "alias": "A",
      "entity": "land",
      "is_location": true,
      "name": "Field A"
    }
  ],
  "key": "loc-a-fixed-asset-ignores-movements",
  "probes": [
    {
      "assert": "is_fixed",
      "subject": "BARN"
    },
    {
      "assert": "current_location_count",
      "subject": "BARN"
    },
    {
      "assert": "current_geometry",
      "subject": "BARN"
    }
  ],
  "title": "A fixed asset keeps its own shape and is placed nowhere, however it is moved",
  "when": [
    {
      "action": "move",
      "against": [
        "BARN"
      ],
      "locations": [
        "A"
      ],
      "status": "done"
    }
  ]
}''')


def test_is_fixed_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_is_fixed_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_is_fixed_authority_was_refined_before_the_first_recording() -> None:
    """AUTHORITY REFINED post-generation (MetaCoding-b0s).

    `add-term` emits every assertion DERIVED with no validated_against — it
    cannot know a term's authority — and the skeleton it writes pins that
    state. The refinement happened here, against the live source
    (2026-07-28): BOUNDARY: a boolean the source states directly on the asset.

    The e6p lesson is why this test is inverted rather than deleted: a BOUND
    term whose ProbeSpec cannot score is a skipped refinement, and it is
    silent. If this fails, the authority regressed and every value recorded
    in the term's name became NO VERDICT.
    """
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert PROBE_CONTRACT[TERM].is_evidence, PROBE_CONTRACT[TERM].unvalidated_reason


def test_is_fixed_is_still_provisional_until_a_sealed_pack_binds_it() -> None:
    """Authority is not binding. A refined authority makes a BOUND value
    scorable; only `ctkr bind-term`, against a sealed recording, binds it."""
    from ctkr.oracle import glossary_provenance

    reason = glossary_provenance.provisional_reason(TERM)
    assert reason == "" or "provisional" in reason.lower()
