"""Generated by `ctkr add-term` for PROVISIONAL action term 'move'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'move'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "A",
      "entity": "land",
      "is_location": true,
      "name": "Field A"
    },
    {
      "alias": "B",
      "entity": "land",
      "is_location": true,
      "name": "Field B"
    },
    {
      "alias": "COW",
      "entity": "animal",
      "name": "Cow"
    }
  ],
  "key": "loc-pending-movement-is-inert",
  "probes": [
    {
      "assert": "is_at_location",
      "other": "A",
      "subject": "COW"
    },
    {
      "assert": "is_at_location",
      "other": "B",
      "subject": "COW"
    }
  ],
  "title": "A pending movement does not change where the asset is; the done one before it still stands",
  "when": [
    {
      "action": "move",
      "against": [
        "COW"
      ],
      "locations": [
        "A"
      ],
      "status": "done"
    },
    {
      "action": "move",
      "against": [
        "COW"
      ],
      "locations": [
        "B"
      ],
      "status": "pending"
    }
  ]
}''')


def test_move_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_move_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers.

    Call widened post-generation with the ABC's signature: a movement names
    MANY assets and MANY locations (MetaCoding-b0s). The farmOS adapter now
    IMPLEMENTS this verb; the ABC's default still raises, which is what this
    pins — an adapter that has not implemented it cannot answer.
    """
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)(['H'], ['L'])
