"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'sensor_private_key'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'sensor_private_key'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a sensor whose private key is the recorded string K"
  ],
  "then": [
    "sensor_private_key of the sensor == K, verbatim"
  ],
  "when": []
}''')


def test_sensor_private_key_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_sensor_private_key_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_sensor_private_key_is_boundary_evidence() -> None:
    """The source STATES this string field directly on the asset at its
    published interface — BOUNDARY transcription (authority refined BEFORE the
    first recording, MetaCoding-ej0 — the e6p lesson), evidence by
    construction. Only explicitly-recorded keys are scoreable: an unstated key
    is oracle-minted per instance and can never reproduce. The term stays
    PROVISIONAL in the provenance registry until a sealed recording binds it."""
    from ctkr.oracle.probes import BOUNDARY, PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.authority == BOUNDARY
    assert spec.is_evidence
