"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'companion_plants'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'companion_plants'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a plant_type term whose companions are the plant types named Basil and Marigold",
    "a second plant_type term whose companions are the single plant type named Basil",
    "a third plant_type term with no companions"
  ],
  "then": [
    "companion_plants of the first term == the names Basil and Marigold",
    "companion_plants of the second term == the single name Basil",
    "companion_plants of the third term == the empty list"
  ],
  "when": []
}''')


def test_companion_plants_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_companion_plants_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_companion_plants_is_validated_evidence() -> None:
    """Validated the lab_test_measurement way (MetaCoding plant-type): the
    multi-valued reference, each referenced term's name, and the source's stated
    relationship order are all stated by the source; the reference-follow, name
    readback, and order preservation add no semantics — so its values may score.
    Unlike lab_test_measurement there is no 'first' selection (the value is ALL
    companions). The validation must stay recorded: dropping validated_against
    silently un-evidences every recorded pack. The term stays PROVISIONAL until a
    sealed recording binds it."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.is_evidence
    assert "stated by the source" in spec.validated_against
