"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'lab_processing_date'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'lab_processing_date'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a land asset"
  ],
  "then": [
    "lab_processing_date of the lab test log == the recorded date",
    "lab_processing_date of a second lab test log recorded with no lab_processed_date == the empty value"
  ],
  "when": [
    "record_log of kind lab_test against the land asset with lab_processed_date set to an absolute date"
  ]
}''')


def test_lab_processing_date_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_lab_processing_date_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_lab_processing_date_is_boundary_evidence() -> None:
    """The source STATES this field at its published interface — BOUNDARY
    transcription (authority refined post-generation, MetaCoding-wgy), evidence
    by construction. The term stays PROVISIONAL in the provenance registry
    until a sealed recording binds it; authority is what makes a BOUND value
    scorable rather than NO VERDICT."""
    from ctkr.oracle.probes import BOUNDARY, PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.authority == BOUNDARY
    assert spec.is_evidence
