"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'sensor_data_stream'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'sensor_data_stream'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a sensor whose data streams are the streams named Soil-A and Soil-B, in that order",
    "a second sensor with no data streams"
  ],
  "then": [
    "sensor_data_stream of the first sensor == [Soil-A, Soil-B] in recorded order",
    "sensor_data_stream of the second sensor == the empty value"
  ],
  "when": []
}''')


def test_sensor_data_stream_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_sensor_data_stream_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_sensor_data_stream_is_validated_evidence() -> None:
    """Validated the companion_plants way (MetaCoding-ej0): the multi-valued
    reference, each referenced stream's name, and the source's stated
    relationship order are all stated by the source; the reference-follow, name
    readback, and order preservation add no semantics — so its values may score.
    There is no 'first' selection (the value is ALL streams). The validation
    must stay recorded: dropping validated_against silently un-evidences every
    recorded pack. The term stays PROVISIONAL until a sealed recording binds
    it. Authority refined BEFORE the first recording — the e6p lesson."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.is_evidence
    assert "stated by the source" in spec.validated_against
