"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'equipment_used'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'equipment_used'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a land asset A",
    "an equipment E1",
    "an equipment E2"
  ],
  "then": [
    "equipment_used(L, other=E1) is the source's answer for the attached equipment",
    "equipment_used(L, other=E2) is the source's answer for the unattached equipment"
  ],
  "when": [
    "record_log activity L against A with equipment [E1]"
  ]
}''')


def test_equipment_used_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_equipment_used_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H', 'X_other')


def test_equipment_used_is_validated_evidence() -> None:
    """Validated the has_parent way (MetaCoding-1cv): the equipment reference
    is stated by the source (FieldHooks.php base field; the log's JSON:API
    equipment relationship) and membership adds no semantics — so its values
    may score. The validation must stay recorded: dropping validated_against
    silently un-evidences every recorded pack."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.is_evidence
    assert "stated by the source" in spec.validated_against
