"""Generated by `ctkr add-term` for PROVISIONAL entity term 'material'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'material'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a material M with descriptor 'Compost'"
  ],
  "then": [
    "the quantity's recorded material type is the asset's \u2014 the quantity_presave fold"
  ],
  "when": [
    "record_log input with a material quantity whose inventory_asset is M"
  ]
}''')


def test_material_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []
