"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'was_at_location'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'was_at_location'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "A",
      "entity": "land",
      "is_location": true,
      "name": "Field A"
    },
    {
      "alias": "B",
      "entity": "land",
      "is_location": true,
      "name": "Field B"
    },
    {
      "alias": "COW",
      "entity": "animal",
      "name": "Cow"
    }
  ],
  "key": "loc-as-of-reads-the-past",
  "probes": [
    {
      "as_of": "2026-03-01T00:00:00+00:00",
      "assert": "was_at_location",
      "other": "A",
      "subject": "COW"
    },
    {
      "as_of": "2026-03-01T00:00:00+00:00",
      "assert": "was_at_location",
      "other": "B",
      "subject": "COW"
    },
    {
      "assert": "is_at_location",
      "other": "B",
      "subject": "COW"
    }
  ],
  "title": "An asset that moved on in June was still in the earlier field in March",
  "when": [
    {
      "action": "move",
      "against": [
        "COW"
      ],
      "at": "2026-01-01T00:00:00+00:00",
      "locations": [
        "A"
      ],
      "status": "done"
    },
    {
      "action": "move",
      "against": [
        "COW"
      ],
      "at": "2026-06-01T00:00:00+00:00",
      "locations": [
        "B"
      ],
      "status": "done"
    }
  ]
}''')


def test_was_at_location_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_was_at_location_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H', 'X_other', 'X_as_of')


def test_was_at_location_authority_was_refined_before_the_first_recording() -> None:
    """AUTHORITY REFINED post-generation (MetaCoding-b0s).

    `add-term` emits every assertion DERIVED with no validated_against — it
    cannot know a term's authority — and the skeleton it writes pins that
    state. The refinement happened against the live source (2026-07-28):
    DERIVED and validated against AssetLocation.php's own getMovementLog rule — farmOS publishes no as-of read at its boundary, so this fold is ours and must be cited.

    Inverted rather than deleted, per the e6p lesson: a BOUND term whose
    ProbeSpec cannot score is a skipped refinement, and it is silent.
    """
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert PROBE_CONTRACT[TERM].is_evidence, PROBE_CONTRACT[TERM].unvalidated_reason
