"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'birth_mother'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'birth_mother'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a dam animal",
    "a second animal that is not the dam",
    "a newborn animal"
  ],
  "then": [
    "birth_mother of the birth log with other=the dam == true",
    "birth_mother of the birth log with other=the second animal == false"
  ],
  "when": [
    "record_birth for the newborn animal with mother set to the dam animal"
  ]
}''')


def test_birth_mother_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_birth_mother_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        # birth_mother is has_parent-shaped: subject birth log + `other` animal.
        getattr(bare(), TERM)('log:birth:u1', 'asset:animal:a1')


def test_birth_mother_is_not_yet_evidence() -> None:
    """PROVISIONAL: derived, unvalidated — its values cannot score."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert not PROBE_CONTRACT[TERM].is_evidence
