"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'crop_family'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'crop_family'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a plant_type term whose crop_family is the family named Solanaceae",
    "a second plant_type term whose crop_family is the family named Brassicaceae",
    "a third plant_type term with no crop_family"
  ],
  "then": [
    "crop_family of the first term == Solanaceae",
    "crop_family of the second term == Brassicaceae",
    "crop_family of the third term == the empty value"
  ],
  "when": []
}''')


def test_crop_family_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_crop_family_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_crop_family_is_validated_evidence() -> None:
    """Validated the laboratory way (MetaCoding plant-type): the single-valued
    reference and the referenced term's name are stated by the source; the
    reference-follow and name readback add no semantics — so its values may
    score. The validation must stay recorded: dropping validated_against
    silently un-evidences every recorded pack. The term stays PROVISIONAL in the
    provenance registry until a sealed recording binds it."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.is_evidence
    assert "stated by the source" in spec.validated_against
