"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'animal_type'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'animal_type'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "COW",
      "descriptor": "Highland Cattle",
      "entity": "animal",
      "name": "Heifer"
    },
    {
      "alias": "EWE",
      "descriptor": "Shetland Sheep",
      "entity": "animal",
      "name": "Ewe"
    }
  ],
  "key": "lin-animal-type-reads-back",
  "probes": [
    {
      "assert": "animal_type",
      "subject": "COW"
    },
    {
      "assert": "animal_type",
      "subject": "EWE"
    }
  ],
  "title": "The kind an animal was created as is the kind the source reports",
  "when": []
}''')


def test_animal_type_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_animal_type_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_animal_type_authority_was_refined_before_the_first_recording() -> None:
    """AUTHORITY REFINED post-generation (MetaCoding-b0s): DERIVED and validated the crop_family way — a source-stated reference followed to the referenced term's own stated name.

    Inverted rather than deleted, per the e6p lesson: a BOUND term whose
    ProbeSpec cannot score is a skipped refinement, and it is silent.
    """
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert PROBE_CONTRACT[TERM].is_evidence, PROBE_CONTRACT[TERM].unvalidated_reason
