"""Generated by `ctkr add-term` for PROVISIONAL action term 'delete_log'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'delete_log'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a land asset"
  ],
  "then": [
    "log_count kind=harvest == 0"
  ],
  "when": [
    "record_log against the land asset",
    "delete_log the recorded log"
  ]
}''')


def test_delete_log_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_delete_log_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')
