"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'material_type_recorded'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'material_type_recorded'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a land A",
    "a material M with descriptor 'Compost'"
  ],
  "then": [
    "material_type_recorded(L) delivers the source's answer (['Compost'] if the fold copied)",
    "a material quantity with no inventory_asset delivers the source's answer (the discriminating contrast)"
  ],
  "when": [
    "record_log input L against A with a material quantity whose inventory_asset is M"
  ]
}''')


def test_material_type_recorded_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_material_type_recorded_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_material_type_recorded_is_validated_evidence() -> None:
    """Validated the has_parent way (MetaCoding-5ln): the material_type
    reference and each term's name are stated by the source; membership and
    name readback add no semantics — so its values may score. The validation
    must stay recorded: dropping validated_against silently un-evidences every
    recorded pack."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.is_evidence
    assert "stated by the source" in spec.validated_against
