"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'laboratory'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'laboratory'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a land asset"
  ],
  "then": [
    "laboratory of the lab test log == the recorded laboratory name",
    "laboratory of a second lab test log recorded with no lab == the empty value"
  ],
  "when": [
    "record_log of kind lab_test against the land asset with lab set to a laboratory name"
  ]
}''')


def test_laboratory_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_laboratory_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_laboratory_is_validated_evidence() -> None:
    """Validated the material_type_recorded / has_parent way (MetaCoding-wgy):
    the reference and each term's name are stated by the source; the
    reference-follow and name readback add no semantics — so its values may
    score. The validation must stay recorded: dropping validated_against
    silently un-evidences every recorded pack. The term stays PROVISIONAL in
    the provenance registry until a sealed recording binds it."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.is_evidence
    assert "stated by the source" in spec.validated_against
