"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'publicly_readable'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'publicly_readable'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a sensor recorded publicly readable (true)",
    "a second sensor recorded NOT publicly readable (false)",
    "a third sensor with no public flag stated"
  ],
  "then": [
    "publicly_readable of the first sensor == true",
    "publicly_readable of the second sensor == false",
    "publicly_readable of the third sensor == the empty value"
  ],
  "when": []
}''')


def test_publicly_readable_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_publicly_readable_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_publicly_readable_is_boundary_evidence() -> None:
    """The source STATES this boolean field directly on the asset at its
    published interface — BOUNDARY transcription (authority refined BEFORE the
    first recording, MetaCoding-ej0 — the e6p lesson), evidence by
    construction. Recorded false is distinct from absent: the boundary's unset
    value is null, not the entity-level default false (validated live). The
    term stays PROVISIONAL in the provenance registry until a sealed recording
    binds it."""
    from ctkr.oracle.probes import BOUNDARY, PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.authority == BOUNDARY
    assert spec.is_evidence
