"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'current_geometry'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'current_geometry'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "A",
      "entity": "land",
      "is_location": true,
      "name": "Field A"
    },
    {
      "alias": "COW",
      "entity": "animal",
      "name": "Cow"
    }
  ],
  "key": "loc-geometry-comes-from-the-movement",
  "probes": [
    {
      "assert": "current_geometry",
      "subject": "COW"
    },
    {
      "assert": "current_geometry",
      "subject": "A"
    }
  ],
  "title": "A movable asset's shape on the ground comes from its own movement, not from the place it was moved to",
  "when": [
    {
      "action": "move",
      "against": [
        "COW"
      ],
      "geometry": "POINT (30 40)",
      "locations": [
        "A"
      ],
      "status": "done"
    }
  ]
}''')


def test_current_geometry_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_current_geometry_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_current_geometry_authority_was_refined_before_the_first_recording() -> None:
    """AUTHORITY REFINED post-generation (MetaCoding-b0s).

    `add-term` emits every assertion DERIVED with no validated_against — it
    cannot know a term's authority — and the skeleton it writes pins that
    state. The refinement happened here, against the live source
    (2026-07-28): BOUNDARY: the shape is stated on the asset; taking the `value` member out of the delivered object drops farmOS's own readings OF it, a representation fold.

    The e6p lesson is why this test is inverted rather than deleted: a BOUND
    term whose ProbeSpec cannot score is a skipped refinement, and it is
    silent. If this fails, the authority regressed and every value recorded
    in the term's name became NO VERDICT.
    """
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert PROBE_CONTRACT[TERM].is_evidence, PROBE_CONTRACT[TERM].unvalidated_reason


def test_current_geometry_is_still_provisional_until_a_sealed_pack_binds_it() -> None:
    """Authority is not binding. A refined authority makes a BOUND value
    scorable; only `ctkr bind-term`, against a sealed recording, binds it."""
    from ctkr.oracle import glossary_provenance

    reason = glossary_provenance.provisional_reason(TERM)
    assert reason == "" or "provisional" in reason.lower()
