"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'assets_at_location_count'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'assets_at_location_count'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "A",
      "entity": "land",
      "is_location": true,
      "name": "Paddock"
    },
    {
      "alias": "B",
      "entity": "land",
      "is_location": true,
      "name": "Empty Field"
    },
    {
      "alias": "COW1",
      "entity": "animal",
      "name": "Cow One"
    },
    {
      "alias": "COW2",
      "entity": "animal",
      "name": "Cow Two"
    },
    {
      "alias": "COW3",
      "entity": "animal",
      "name": "Cow Three"
    }
  ],
  "key": "loc-what-is-in-the-paddock",
  "probes": [
    {
      "assert": "assets_at_location_count",
      "subject": "A"
    },
    {
      "assert": "assets_at_location_count",
      "subject": "B"
    }
  ],
  "title": "Two of three animals moved to the paddock: the paddock holds two and the other field none",
  "when": [
    {
      "action": "move",
      "against": [
        "COW1",
        "COW2"
      ],
      "locations": [
        "A"
      ],
      "status": "done"
    }
  ]
}''')


def test_assets_at_location_count_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_assets_at_location_count_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H', 'X_as_of')


def test_assets_at_location_count_authority_was_refined_before_the_first_recording() -> None:
    """AUTHORITY REFINED post-generation (MetaCoding-b0s).

    `add-term` emits every assertion DERIVED with no validated_against — it
    cannot know a term's authority — and the skeleton it writes pins that
    state. The refinement happened against the live source (2026-07-28):
    DERIVED and validated: the MEMBERSHIP stays farmOS's in both modes, only the ENUMERATION is ours, and its bundle set is read from the source's own /api index.

    Inverted rather than deleted, per the e6p lesson: a BOUND term whose
    ProbeSpec cannot score is a skipped refinement, and it is silent.
    """
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert PROBE_CONTRACT[TERM].is_evidence, PROBE_CONTRACT[TERM].unvalidated_reason
