"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'quantity_label'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'quantity_label'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    {
      "alias": "A",
      "entity": "land",
      "name": "Bed"
    }
  ],
  "key": "qty-label-tells-two-alike-measurements-apart",
  "probes": [
    {
      "assert": "quantity_label",
      "subject": "Q1"
    },
    {
      "assert": "quantity_label",
      "subject": "Q2"
    }
  ],
  "title": "Two weights of the same unit are told apart by what each is a measurement of",
  "when": [
    {
      "action": "record_log",
      "against": [
        "A"
      ],
      "alias": "L",
      "kind": "harvest",
      "name": "Two pickings",
      "quantities": [
        {
          "alias": "Q1",
          "label": "morning",
          "measure": "weight",
          "unit": "kilogram",
          "value": 3
        },
        {
          "alias": "Q2",
          "label": "evening",
          "measure": "weight",
          "unit": "kilogram",
          "value": 7
        }
      ],
      "status": "done"
    }
  ]
}''')


def test_quantity_label_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_quantity_label_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_quantity_label_authority_was_refined_before_the_first_recording() -> None:
    """AUTHORITY REFINED post-generation (MetaCoding-b0s): BOUNDARY — a string the source states directly on the quantity.

    Inverted rather than deleted, per the e6p lesson: a BOUND term whose
    ProbeSpec cannot score is a skipped refinement, and it is silent.
    """
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert PROBE_CONTRACT[TERM].is_evidence, PROBE_CONTRACT[TERM].unvalidated_reason
