"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'structure_kind'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'structure_kind'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a structure whose descriptor is greenhouse",
    "a second structure whose descriptor is building",
    "a third structure with no descriptor stated"
  ],
  "then": [
    "structure_kind of the first structure == greenhouse",
    "structure_kind of the second structure == building",
    "structure_kind of the third structure == other (the adapter's stated fallback, delivered by the boundary)"
  ],
  "when": []
}''')


def test_structure_kind_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_structure_kind_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_structure_kind_is_boundary_evidence() -> None:
    """The source STATES this required list_string directly on the asset at
    its published interface — BOUNDARY transcription (authority refined
    BEFORE the first recording, MetaCoding-xq7 — the e6p lesson), evidence by
    construction. The term stays PROVISIONAL in the provenance registry until
    a sealed recording binds it."""
    from ctkr.oracle.probes import BOUNDARY, PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.authority == BOUNDARY
    assert spec.is_evidence


def test_structure_descriptor_is_gated_against_the_closed_set() -> None:
    """An unrecognised structure descriptor would 422 at the boundary
    (list_string, required, closed allowed values — validated live), so it
    must fail loudly at author time, the land discipline. A member of the
    set passes; the fallback path (no descriptor) stays legal."""
    from ctkr.oracle.fixtures import (
        GivenStep, Provenance, SemanticFixture, ThenAssertion, validate_fixture,
    )

    def fx(descriptor: str) -> SemanticFixture:
        return SemanticFixture(
            title="structure descriptor gate",
            glossary_terms=["structure", "structure_kind"],
            given=[GivenStep(entity="structure", alias="S", name="Barnish",
                             descriptor=descriptor)],
            when=[],
            then=[ThenAssertion(**{"assert": "structure_kind"}, subject="S",
                                value="other", witness="w1")],
            provenance=Provenance(source_system="farmOS", source_version="4.x",
                                  flow="t", recorded_at="2026-07-23T00:00:00+00:00",
                                  evidence_class="scoring"),
        )

    bad = [e for e in validate_fixture(fx("barn"))
           if "structure descriptor" in e.message]
    assert bad, "unrecognised structure descriptor must be rejected"
    for legal in ("greenhouse", "building", "other", ""):
        assert not [e for e in validate_fixture(fx(legal))
                    if "structure descriptor" in e.message]
