"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'days_to_maturity'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'days_to_maturity'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a plant_type term with maturity_days set to 85",
    "a second plant_type term with no maturity_days"
  ],
  "then": [
    "days_to_maturity of the first term == 85",
    "days_to_maturity of the second term == the empty value"
  ],
  "when": []
}''')


def test_days_to_maturity_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_days_to_maturity_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_days_to_maturity_is_boundary_evidence() -> None:
    """The source STATES this integer field directly on the term at its
    published interface — BOUNDARY transcription (authority refined
    post-generation, MetaCoding plant-type), evidence by construction. The term
    stays PROVISIONAL in the provenance registry until a sealed recording binds
    it; authority is what makes a BOUND value scorable rather than NO VERDICT."""
    from ctkr.oracle.probes import BOUNDARY, PROBE_CONTRACT

    spec = PROBE_CONTRACT[TERM]
    assert spec.authority == BOUNDARY
    assert spec.is_evidence
