"""Generated by `ctkr add-term` for PROVISIONAL assertion term 'material_quantity'.

Pins what the plumbing guarantees BEFORE any implementation exists:
the term is registered, the contract has no holes, and nothing can
fake an answer for it. Replace the discriminating flow below with a
recorded fixture once the term is bound.
"""

import json

import pytest

from ctkr.oracle import glossary
from ctkr.oracle.probes import contract_gaps

TERM = 'material_quantity'

# The spec's discriminating flow — the scenario a recording must exercise
# for `ctkr bind-term` to flip this term provisional -> bound.
DISCRIMINATING_FLOW = json.loads(r'''{
  "given": [
    "a land asset"
  ],
  "then": [
    "quantity_recorded",
    "material_quantity"
  ],
  "when": [
    "record_log with a material quantity"
  ]
}''')


def test_material_quantity_is_a_registered_glossary_term() -> None:
    assert TERM in glossary.all_terms()
    assert contract_gaps() == []


def test_material_quantity_unimplemented_stub_fails_loudly() -> None:
    """The fake-green rule: an unimplemented surface RAISES, never answers."""
    from ctkr.oracle.adapter import AdapterError, ImplementationAdapter

    bare = type('_Bare', (ImplementationAdapter,), {})
    bare.__abstractmethods__ = frozenset()
    with pytest.raises(AdapterError):
        getattr(bare(), TERM)('H')


def test_material_quantity_is_not_yet_evidence() -> None:
    """PROVISIONAL: derived, unvalidated — its values cannot score."""
    from ctkr.oracle.probes import PROBE_CONTRACT

    assert not PROBE_CONTRACT[TERM].is_evidence
