/**
 * Integration tests for hom-profile reads + KNN.
 *
 * Runs against /tmp/metacoding-scip/ if hom_profiles.parquet is present;
 * skips cleanly otherwise. The artifact is generated by:
 *   uv run python -m ctkr hom-profiles --data-dir /tmp/metacoding-scip
 */

import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { openCtkrArtifacts, type CtkrHandle } from "./artifacts.ts";
import { cosineDistance } from "./homProfile.ts";

const TEST_DATA_DIR = "/tmp/metacoding-scip";
const dataAvailable = await Bun.file(
  `${TEST_DATA_DIR}/ctkr/hom_profiles.parquet`,
).exists();

function maybeSkip(name: string, fn: () => Promise<void>): void {
  test(name, async () => {
    if (!dataAvailable) {
      console.log(
        `SKIP: ${name} — ${TEST_DATA_DIR}/ctkr/hom_profiles.parquet not found. ` +
          `Run: uv run python -m ctkr hom-profiles --data-dir ${TEST_DATA_DIR}`,
      );
      return;
    }
    await fn();
  });
}

describe("CtkrHandle.homProfiles + homProfilesKnn (integration)", () => {
  let handle: CtkrHandle;

  beforeAll(async () => {
    if (!dataAvailable) return;
    handle = await openCtkrArtifacts(TEST_DATA_DIR);
  });

  afterAll(async () => {
    if (!dataAvailable) return;
    await handle.close();
  });

  maybeSkip("manifest advertises hom_profiles", async () => {
    const mf = await handle.manifest();
    expect(mf.hom_profiles).toBe(true);
    expect(mf.n_hom_profiles).toBeGreaterThan(0);
    expect(mf.profile_vec_dim).toBe(28);
  });

  maybeSkip("homProfiles({ limit }) returns capped rows with the right shape", async () => {
    const rows = await handle.homProfiles({ limit: 5 });
    expect(rows.length).toBe(5);
    for (const row of rows) {
      expect(typeof row.symbol_id).toBe("string");
      expect(typeof row.repo).toBe("string");
      expect(typeof row.qualified_name).toBe("string");
      expect(Array.isArray(row.profile_vec)).toBe(true);
      expect(row.profile_vec.length).toBe(28);
      for (const c of row.profile_vec) {
        expect(typeof c).toBe("number");
        expect(c).toBeGreaterThanOrEqual(0);
      }
    }
  });

  maybeSkip("homProfileBySymbolId returns a single row matching the id", async () => {
    const seed = (await handle.homProfiles({ limit: 1 }))[0]!;
    const row = await handle.homProfileBySymbolId(seed.symbol_id);
    expect(row).not.toBeNull();
    expect(row!.symbol_id).toBe(seed.symbol_id);
    expect(row!.profile_vec).toEqual(seed.profile_vec);
  });

  maybeSkip("homProfileBySymbolId returns null for unknown ids", async () => {
    const row = await handle.homProfileBySymbolId("definitely-not-a-symbol-id");
    expect(row).toBeNull();
  });

  maybeSkip(
    "homProfilesKnn returns k results sorted by cosine distance ascending, excluding seed",
    async () => {
      // Pick a seed that has at least some non-zero edges so KNN is meaningful.
      // Scan the first 1000 rows for a non-isolate.
      const candidates = await handle.homProfiles({ limit: 1000 });
      const seed = candidates.find((r) =>
        r.profile_vec.some((c) => c > 0),
      );
      expect(seed).toBeDefined();

      const k = 5;
      const results = await handle.homProfilesKnn({
        seedId: seed!.symbol_id,
        k,
      });

      expect(results.length).toBeGreaterThan(0);
      expect(results.length).toBeLessThanOrEqual(k);

      // Seed excluded from results.
      for (const r of results) {
        expect(r.symbol_id).not.toBe(seed!.symbol_id);
      }

      // Ascending distance order.
      for (let i = 1; i < results.length; i++) {
        expect(results[i]!.distance).toBeGreaterThanOrEqual(
          results[i - 1]!.distance,
        );
      }

      // Distances are in [0, 2] (cosine distance range).
      for (const r of results) {
        expect(r.distance).toBeGreaterThanOrEqual(0);
        expect(r.distance).toBeLessThanOrEqual(2 + 1e-9);
      }
    },
  );

  maybeSkip(
    "homProfilesKnn first-result distance matches direct cosineDistance",
    async () => {
      // Pick a seed with edges, then take its top match and verify the
      // distance reported by DuckDB matches what we compute in TS over
      // the same raw vectors. Catches dim-ordering bugs and any silent
      // cast-loss in the DuckDB query.
      const candidates = await handle.homProfiles({ limit: 1000 });
      const seed = candidates.find((r) =>
        r.profile_vec.some((c) => c > 0),
      )!;

      const knn = await handle.homProfilesKnn({ seedId: seed.symbol_id, k: 1 });
      expect(knn.length).toBe(1);
      const topMatch = knn[0]!;
      const matchRow = await handle.homProfileBySymbolId(topMatch.symbol_id);
      expect(matchRow).not.toBeNull();

      const localDistance = cosineDistance(seed.profile_vec, matchRow!.profile_vec);
      expect(topMatch.distance).toBeCloseTo(localDistance, 5);
    },
  );

  maybeSkip(
    "homProfilesKnn { sameRepoOnly } restricts to seed's repo",
    async () => {
      const candidates = await handle.homProfiles({ limit: 1000 });
      const seed = candidates.find((r) =>
        r.profile_vec.some((c) => c > 0),
      )!;
      const results = await handle.homProfilesKnn({
        seedId: seed.symbol_id,
        k: 5,
        sameRepoOnly: true,
      });
      for (const r of results) {
        expect(r.repo).toBe(seed.repo);
      }
    },
  );

  maybeSkip(
    "homProfilesKnn { differentRepoOnly } excludes seed's repo",
    async () => {
      const candidates = await handle.homProfiles({ limit: 1000 });
      const seed = candidates.find((r) =>
        r.profile_vec.some((c) => c > 0),
      )!;
      const results = await handle.homProfilesKnn({
        seedId: seed.symbol_id,
        k: 5,
        differentRepoOnly: true,
      });
      for (const r of results) {
        expect(r.repo).not.toBe(seed.repo);
      }
    },
  );

  maybeSkip(
    "homProfilesKnn rejects sameRepoOnly + differentRepoOnly together",
    async () => {
      const seed = (await handle.homProfiles({ limit: 1 }))[0]!;
      await expect(
        handle.homProfilesKnn({
          seedId: seed.symbol_id,
          k: 1,
          sameRepoOnly: true,
          differentRepoOnly: true,
        }),
      ).rejects.toThrow(/mutually exclusive/);
    },
  );

  maybeSkip(
    "homProfilesKnn throws when seedId is not in the artifact",
    async () => {
      await expect(
        handle.homProfilesKnn({ seedId: "no-such-symbol", k: 1 }),
      ).rejects.toThrow(/not found/);
    },
  );
});
