/**
 * AUTO-GENERATED — do not edit by hand.
 * Generated by: bun run codegen:ctkr-types
 * Source of truth: ctkr/ctkr/schema.py + ctkr/ctkr/schema_l3.py
 *
 * To regenerate:
 *   bun run codegen:ctkr-types
 *
 * To check for drift against hand-written types.ts:
 *   bun run codegen:check
 */

/**
 * Top-level pointer file for the ``.metacoding/ctkr/`` directory.
 *
 * Lives at ``.metacoding/ctkr/manifest.json``. Records which artifacts
 * are present, when they were generated, and what version of this
 * schema they were validated against. Cheap to read; tooling should
 * consult it before assuming an artifact exists.
 */
export interface ArtifactManifest {
    alphabet_coverage?:  { [key: string]: { [key: string]: any } } | null;
    centrality?:         boolean;
    data_shapes?:        boolean;
    embedding_dim?:      number | null;
    embeddings?:         boolean;
    functor_edges?:      boolean;
    functors?:           boolean;
    generated_at:        string;
    hom_profiles?:       boolean;
    interfaces?:         boolean;
    kind_weights?:       { [key: string]: number } | null;
    metacoding_data_dir: string;
    motif_instances?:    boolean;
    motifs?:             boolean;
    n_data_shapes?:      number;
    n_functor_edges?:    number;
    n_functors?:         number;
    n_hom_profiles?:     number;
    n_interfaces?:       number;
    n_motif_instances?:  number;
    n_motifs?:           number;
    n_operads?:          number;
    n_presentations?:    number;
    n_subsystem_cards?:  number;
    n_subsystems?:       number;
    n_symbols?:          number;
    nn_index?:           boolean;
    notes?:              null | string;
    operads?:            boolean;
    presentations?:      boolean;
    profile_depth?:      number | null;
    profile_vec_dim?:    number | null;
    schema_version?:     number;
    shape_pds?:          boolean;
    spectral_clusters?:  boolean;
    subsystem_cards?:    boolean;
    subsystem_members?:  boolean;
    subsystems?:         boolean;
    wasserstein_h1?:     boolean;
    [property: string]: any;
}

/**
 * Per-symbol centrality scores produced by L1/S2.
 *
 * All three measures are normalized to [0, 1] within the source graph.
 * ``betweenness`` is approximate when computed with sampling
 * (``k < |N|``) — recorded as the same column for consistency, with
 * the sampling factor noted in :attr:`ArtifactManifest.notes`.
 */
export interface CentralityRow {
    articulation?:   boolean;
    betweenness:     number;
    eigenvector:     number;
    pagerank:        number;
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * One field of a type in the boundary/internal data vocabulary (§3).
 *
 * One row per ``(subsystem_id, type_symbol_id, field)``. A type is a
 * **boundary** shape (``boundary=True``) when it crosses the interface (a
 * port must reproduce it semantically) or **internal** otherwise (a port may
 * restructure it — accidental-unless-persistent, §6.1). ``read_by_*`` /
 * ``written_by_*`` record per-field flow direction: a field written only by
 * the subsystem and read externally is an *output* contract; written
 * externally and read internally is an *input*. Fieldless boundary types get a
 * single row with null ``field_*`` so the type is still recorded.
 *
 * Recovered from ``READS_FIELD`` / ``WRITES_FIELD`` (flow), ``TYPE_OF`` (a
 * field's declared type), ``CONSTRUCTS`` (``constructed_by``) — the
 * MetaCoding-e54/3s5/9le data alphabet. Coverage is per-lane uneven; the run's
 * ``ArtifactManifest.alphabet_coverage`` note says whether a thin shapes
 * section is an extractor gap rather than an absent data model.
 */
export interface DataShapeRow {
    boundary:            boolean;
    constructed_by:      string[];
    field_name:          null | string;
    field_symbol_id:     null | string;
    field_type:          null | string;
    read_by_external:    boolean;
    read_by_internal:    boolean;
    repo:                string;
    schema_version?:     number;
    subsystem_id:        string;
    type_qualified_name: string;
    type_symbol_id:      string;
    written_by_external: boolean;
    written_by_internal: boolean;
    [property: string]: any;
}

/**
 * One symbol's embedding vector.
 *
 * Produced by L1/C1 (node2vec / GraphSAGE). All vectors in a single
 * ``embeddings.parquet`` MUST share a dimension; that dimension is
 * recorded in ``ArtifactManifest.embedding_dim``.
 */
export interface EmbeddingRow {
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    vec:             number[];
    [property: string]: any;
}

/**
 * One snippet of source evidence for a labeled pattern.
 *
 * Multiple rows per ``pattern_id``: each row points to a concrete
 * location in some repo whose code instantiates the pattern. The
 * snippet itself is materialized so the JSONL is self-contained for
 * review — no re-resolution needed against the indexed sources.
 */
export interface EvidenceRow {
    /**
     * Optional surrounding-symbol qualified_name (e.g. the enclosing class or function). Lets
     * reviewers orient without opening the file.
     */
    context?:        null | string;
    file:            string;
    line_range:      LineRangeObject;
    pattern_id:      string;
    repo:            string;
    schema_version?: number;
    snippet:         string;
    [property: string]: any;
}

/**
 * Inclusive line span in a source file.
 */
export interface LineRangeObject {
    end:   number;
    start: number;
    [property: string]: any;
}

/**
 * One object↦object correspondence — a weighted meta-graph edge (Phase 2c).
 *
 * Produced alongside ``FunctorRow`` by the functor-discovery runner. This is
 * the Phase 2c meta-graph edge stream (MetaCoding-at0): Louvain's nodes are
 * ``(repo, symbol_id)`` across the corpus and each row here is one weighted
 * meta-edge. ``functor_id`` is the FK back into ``functors.parquet``.
 *
 * Null semantics: ``pair_fidelity`` is ``-1`` when the source has no internal
 * incident edges (no structural evidence — consumers must NOT read this as
 * 1.0). ``margin`` is the σ gap to the best unaccepted alternative for this
 * source; low margin = the assignment was a near-coin-flip among lookalikes
 * (expected often under BORDERLINE seeds).
 */
export interface FunctorEdgeRow {
    dst_qualified_name: string;
    dst_repo:           string;
    dst_symbol_id:      string;
    functor_id:         string;
    is_ambiguous?:      boolean;
    margin:             number;
    n_edges_incident:   number;
    n_edges_preserved:  number;
    pair_fidelity:      number;
    schema_version?:    number;
    similarity:         number;
    src_qualified_name: string;
    src_repo:           string;
    src_symbol_id:      string;
    [property: string]: any;
}

/**
 * One discovered (approximate) functor ``F : C_src → C_dst`` — Phase 2b.
 *
 * Produced by the TS functor-discovery runner (``src/ctkr/functorRunner.ts``,
 * MetaCoding §6 Task 3). One row per ``(repo_src, repo_dst, config)`` — a
 * *directed* pair, so both directions of a repo pair appear as separate rows.
 * Python never writes these (TS owns Phase 2 per MetaCoding-p4b); this model
 * is the canonical schema authority so the codegen'd TS mirror and any
 * Python-side L3/analysis readers agree on shape and column order.
 *
 * Null semantics (§1.3): metrics with no evidence are stored as the sentinel
 * ``-1.0`` (a real float on disk — Parquet floats are not nullable in the
 * ``-1`` convention this artifact set uses) and surfaced as ``null`` by
 * consumers. ``fidelity`` is ``-1`` when ``n_edges_internal == 0`` (an
 * edgeless domain preserves nothing and proves nothing — it must fail any
 * ``min_fidelity > 0`` filter, NOT read as perfect 1.0). ``path_fidelity_2``
 * is ``-1`` when the 2-path composition diagnostic was not computed.
 * ``cycle_consistency`` is ``-1`` when the reverse-direction functor was not
 * computed under the same config.
 */
export interface FunctorRow {
    ambiguity_mass?:   number;
    config:            string;
    coverage:          number;
    cycle_consistency: number;
    fidelity:          number;
    functor_id:        string;
    generated_at:      string;
    n_edges_internal:  number;
    n_edges_preserved: number;
    n_mapped:          number;
    n_objects_src:     number;
    path_fidelity_2:   number;
    repo_dst:          string;
    repo_src:          string;
    schema_version?:   number;
    [property: string]: any;
}

/**
 * One symbol's hom-profile — raw integer edge counts by (kind, direction).
 *
 * Produced by L1 (``ctkr hom-profiles``, MetaCoding-23q.1). The vector
 * is stored at **maximal precision** as unsigned integer counts (no
 * L1-normalisation, no quantisation, no kinds_filter baked into the
 * numbers). Per ``docs/notes/entropy-as-dial.md`` granularity is a
 * caller-tunable knob, so downstream tools re-normalise / discretize
 * at query time rather than the writer baking a choice into the bytes.
 *
 * Vector dimension is ``2 * len(EDGE_KINDS)`` from
 * ``ctkr.graph_loader.EDGE_KINDS`` (currently 28). Ordering convention:
 * for each ``ek in EDGE_KINDS``, the ``(ek, "in")`` slot precedes the
 * ``(ek, "out")`` slot. The canonical ``_DIMS`` list in
 * ``ctkr.hom_profiles`` is the single source of truth for the order.
 */
export interface HomProfileRow {
    profile_vec:     number[];
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * One cross-boundary contract morphism (subsystem-extraction §3, Stage B).
 *
 * A subsystem's interface contract is not written down anywhere — it *is* the
 * set of morphisms crossing its boundary. One row per aggregated
 * ``(subsystem_id, direction, internal_symbol_id, external_symbol_id,
 * edge_kind)``:
 *
 * - ``direction="provides"`` — an external symbol references an internal one
 * (the API surface); ``internal_symbol_id`` is the export, ``edge_kind`` its
 * usage mode (``REFERENCES``/``CALLS`` in = invoked, ``IMPLEMENTS`` in =
 * extension point, ``TYPE_OF``/``RETURNS_TYPE`` in = used as a type,
 * ``CONSTRUCTS`` in = instantiated).
 * - ``direction="consumes"`` — an internal symbol references an external one
 * (the dependency surface); ``external_subsystem_id`` gives the
 * subsystem-level topology (null = external package / unpartitioned).
 *
 * ``CONTAINS`` scaffolding is excluded (§6.1 tier-A). ``internal_export_*``
 * rolls the (possibly nested) internal symbol up to its top-level declaration
 * — the re-implementer's actual export surface — computed name-blind from the
 * qualified-name path. The raw ``internal_symbol_id`` stays maximal-precision.
 */
export interface InterfaceRow {
    direction:                      Direction;
    edge_count:                     number;
    edge_kind:                      string;
    external_qualified_name:        string;
    external_subsystem_id:          null | string;
    external_symbol_id:             string;
    internal_export_qualified_name: string;
    internal_export_symbol_id:      null | string;
    internal_qualified_name:        string;
    internal_symbol_id:             string;
    repo:                           string;
    schema_version?:                number;
    subsystem_id:                   string;
    [property: string]: any;
}

export type Direction = "provides" | "consumes";

/**
 * Inclusive line span in a source file.
 */
export interface LineRange {
    end:   number;
    start: number;
    [property: string]: any;
}

/**
 * One concrete occurrence of a motif in the corpus.
 *
 * Multiple rows per ``motif_id``; links back to the originating
 * symbol(s) so an evidence-fetcher (L3/F3) can pull snippets.
 */
export interface MotifInstanceRow {
    file:            string;
    line:            number;
    motif_id:        string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * One frequent typed subgraph discovered by L1/C2.
 *
 * ``signature`` is the canonical serialization of the motif's graph
 * structure (a typed-edge-list string, deterministic across runs of
 * the miner). It is the join key into ``motif_instances.parquet``.
 */
export interface MotifRow {
    edge_kinds:      EdgeKind[];
    motif_id:        string;
    repo_coverage:   string[];
    schema_version?: number;
    signature:       string;
    size_edges:      number;
    size_nodes:      number;
    support:         number;
    [property: string]: any;
}

export type EdgeKind = "CALLS" | "REFERENCES" | "EXTENDS" | "IMPLEMENTS" | "OVERRIDES" | "INJECTS" | "CONTAINS" | "IMPORTS" | "ANNOTATES" | "TYPE_OF";

/**
 * Metadata sidecar for the opaque ``nn_index/`` directory.
 *
 * The binary index itself (FAISS or hnswlib) is not a parquet table.
 * This sidecar records what's inside so callers don't have to
 * introspect the binary.
 */
export interface NNIndexMeta {
    backend:       Backend;
    built_at:      string;
    embedding_dim: number;
    /**
     * Relative path to the embeddings.parquet this index was built from. Used to detect
     * staleness when embeddings are regenerated.
     */
    embeddings_source: string;
    metric:            Metric;
    n_symbols:         number;
    schema_version?:   number;
    [property: string]: any;
}

export type Backend = "faiss" | "hnswlib";

export type Metric = "cosine" | "l2" | "ip";

/**
 * One recovered composition operation of a subsystem — a relation (§4.3, T4).
 *
 * Phase 2d operad recovery, scoped single-repo and per-subsystem. The role
 * inventory (``presentations.parquet``, T3) gives a subsystem's *generators*
 * (role classes); this artifact gives its *relations* — the composition
 * algebra a re-implementer most needs and most lacks: not the pieces, but how
 * they combine. One row per ``(subsystem_id, view, operation_id)``.
 *
 * Operations are mined by projecting the subsystem's actual typed call/
 * reference paths onto role classes (``parseConfig → validateSchema →
 * applyDefaults`` becomes the role-path ``Loader ∘ Validator ∘ Defaulter``)
 * and keeping the role-paths that recur with ``support ≥ k``. Three
 * ``op_kind`` families:
 *
 * - ``"path"`` — a recurring linear role-path (sequential composition). The
 * terminal role is ``output_role``; the preceding roles are ``input_roles``
 * (order preserved); ``arity`` = number of composition steps = len(path)-1.
 * An arity-1 path is a single generator ``R_i → R_j``.
 * - ``"fan_in"`` — an n-ary combination: a target role invoked/produced by
 * combining ``arity`` distinct source roles (the multi-fan-in / wiring-
 * diagram reading, Fong & Spivak ch. 6). ``input_roles`` is the sorted set
 * of source roles; ``output_role`` the target; ``arity`` = |input_roles|.
 * - ``"non_operadic"`` — a recorded *law violation*, not a valid operation
 * (ct-pipeline §2d: "non-operadic composition is interesting in itself" —
 * recorded, never discarded). ``violation_kind`` says which law broke:
 * ``"missing_composite"`` (two generators ``R_i→R_j`` and ``R_j→R_k`` both
 * recur, so they compose at role level, but the predicted 2-step composite
 * ``R_i→R_j→R_k`` is never actually observed — role-composability without
 * instance-composition) or ``"back_call_cycle"`` (both ``R_i→R_j`` and
 * ``R_j→R_i`` recur — an observed 2-cycle, the "Worker never calls
 * Orchestrator back except through Callback" non-law).
 *
 * ``support`` is the number of concrete instances backing the operation.
 * ``edge_kinds`` are the distinct typed-edge kinds along the composition.
 * ``exemplar_paths`` are up to a few concrete qualified-name paths (``a -> b
 * -> c``) so a re-implementer sees the operation, not just its role types.
 *
 * ``is_boundary_op`` (the T4 boundary flag) is True when any of the
 * operation's roles participates in the subsystem's interface (a role with
 * non-empty ``interface_participation`` in ``presentations.parquet``, which in
 * turn joins ``interfaces.parquet``, T2). Boundary operations are the
 * subsystem's **protocol** — the order-of-operations contract external callers
 * depend on (init-before-use, acquire-then-release), the composition laws a
 * port breaks first and silently.
 *
 * ``associative_observed`` records the empirical associativity/closure law for
 * ``path`` ops of arity ≥ 2: True when every composable generator pair whose
 * middle role is shared realizes its predicted 2-step composite as an observed
 * operation. ``law_violations`` counts the composable generator pairs at this
 * operation whose composite is *missing* (0 for a fully-closed op). For
 * ``fan_in`` ops the law fields are trivially satisfied
 * (``associative_observed=True``, ``law_violations=0``); for ``non_operadic``
 * rows ``associative_observed=False`` and ``law_violations=1``.
 *
 * ``view`` selects which role quotient (``"orbit"`` = exact-profile WL classes,
 * conservative; ``"similarity"`` = cosine-threshold working classes) the
 * role-paths were projected through — the same dial as ``presentations.parquet``.
 * ``invariance_tier`` is ``"I"`` (composition laws over roles are tier-I per
 * §6.1 — a port must preserve them). ``operation_id`` is content-addressed
 * (blake3 of subsystem_id + view + op_kind + role signature + config) so
 * re-runs over the same partition + roles are byte-identical and
 * ``generated_at`` never enters the id.
 */
export interface OperadRow {
    arity:                number;
    associative_observed: boolean;
    config:               string;
    edge_kinds:           string[];
    exemplar_paths:       string[];
    generated_at:         string;
    input_roles:          string[];
    invariance_tier:      string;
    is_boundary_op:       boolean;
    law_violations:       number;
    op_kind:              OpKind;
    operation_id:         string;
    output_role:          string;
    repo:                 string;
    schema_version?:      number;
    subsystem_id:         string;
    support:              number;
    view:                 View;
    violation_kind:       string;
    [property: string]: any;
}

export type OpKind = "path" | "fan_in" | "non_operadic";

export type View = "orbit" | "similarity";

/**
 * One labeled structural element produced by an L3 labeler.
 *
 * ``source_ref`` is a foreign key into the L1 artifact named by
 * ``source_kind``:
 *
 * - ``source_kind == "motif"``       → ``source_ref`` is a ``motif_id``
 * - ``source_kind == "role-cluster"`` → ``source_ref`` is a cluster id
 * - ``source_kind == "analogy"``      → ``source_ref`` is an analogy-pair id
 *
 * ``instances`` lists the concrete symbol_ids that participate; for
 * motifs these are the anchor symbols (matching
 * ``MotifInstanceRow.symbol_id`` in schema.py). The corresponding
 * code-evidence snippets live in ``evidence.jsonl``.
 *
 * Mandatory provenance fields — ``llm_model``, ``llm_temperature``,
 * ``prompt_version``, ``schema_version`` — make every label
 * invalidatable on prompt or model changes without re-running L1.
 */
export interface PatternRow {
    /**
     * LLM-reported or post-hoc confidence in [0, 1].
     */
    confidence: number;
    /**
     * One-paragraph explanation of what the pattern does and why it recurs.
     */
    description: string;
    /**
     * Optional explicit list of evidence row keys (pattern_id is the primary join; this field
     * is for cases where evidence rows are themselves uniquely keyed). May be empty if the join
     * is purely by pattern_id.
     */
    evidence_ids?: string[];
    generated_at:  string;
    /**
     * Symbol IDs (anchor symbols) participating in this pattern.
     */
    instances: string[];
    /**
     * Short canonical name (~3 words). Reused as a pattern key in downstream
     * cross-instantiation synthesis.
     */
    label:           string;
    llm_model:       string;
    llm_temperature: number;
    pattern_id:      string;
    prompt_version:  string;
    schema_version?: number;
    source_kind:     SourceKind;
    source_ref:      string;
    [property: string]: any;
}

export type SourceKind = "motif" | "role-cluster" | "analogy" | "subsystem" | "role-class" | "operad-op" | "interface-export" | "data-shape" | "nl-only";

/**
 * One role class of a subsystem's presentation — a generator (§4.1, T3).
 *
 * The role inventory quotients a subsystem's members by hom-profile
 * equivalence (**depth 1** — the role-*surfacing* dial per MetaCoding-4ty: at
 * depth 1 you *want* the automorphism orbits, so 14 concrete validators
 * collapse to one ``Validator`` generator). One row per
 * ``(subsystem_id, view, role_id)``.
 *
 * Two views are always emitted (the design's "orbit-exact vs
 * similarity-cluster both emitted"):
 *
 * - ``view="orbit"`` — the **conservative** quotient: members with a
 * *byte-identical* depth-1 profile vector share a class (exact
 * Weisfeiler-Leman orbits, the WL classes from the 2-hop work). No
 * threshold; ``granularity="exact"``; ``persistence=1.0`` (exact classes
 * are definitional, not swept).
 * - ``view="similarity"`` — the **working** quotient: cosine-threshold
 * connected-components over the max-precision profile vectors at a default
 * threshold, with a threshold sweep supplying ``persistence`` (mean
 * within-class co-association across the sweep, exactly the subsystems.py
 * robustness story). ``granularity`` records the default threshold.
 *
 * ``role_id`` is content-addressed (blake3 of subsystem_id + view + config +
 * sorted-member digest) so re-runs over the same partition are byte-identical
 * and ``generated_at`` never enters the id. ``profile_centroid`` is the mean
 * depth-1 profile of the members (the role's hom-profile centroid);
 * ``exemplar_symbol_id`` is the member nearest that centroid (max cosine;
 * ties by min symbol_id) — every role has an exemplar (a re-implementer needs
 * the *Validator* role + one concrete instance, not all 14). Zero-profile
 * (edgeless) members share a single "isolated" class per view — the honest
 * structural floor (§2.3): structure cannot discriminate them, so they are
 * not exploded into singletons.
 *
 * ``interface_participation`` is the subset of ``{"provides","consumes"}`` any
 * member of the class occupies in the subsystem's interface (join against
 * ``interfaces.parquet``, T2). The re-implementer's first question about any
 * role is whether it is public; empty when interfaces were not extracted or
 * the class is purely internal.
 */
export interface PresentationRow {
    cardinality:             number;
    config:                  string;
    exemplar_qualified_name: string;
    exemplar_symbol_id:      string;
    generated_at:            string;
    granularity:             string;
    interface_participation: string[];
    members:                 string[];
    persistence:             number;
    profile_centroid:        number[];
    profile_depth:           number;
    repo:                    string;
    role_id:                 string;
    schema_version?:         number;
    subsystem_id:            string;
    view:                    View;
    [property: string]: any;
}

/**
 * Persistent-homology shape signature for one (repo, homology-dim) pair.
 *
 * Produced by L1/S1. ``persistence_pairs`` is encoded as flat parallel
 * lists rather than a list-of-tuples because Parquet's list<list<...>>
 * support varies across readers.
 */
export interface ShapePDRow {
    birth:           number[];
    death:           number[];
    dim:             number;
    repo:            string;
    schema_version?: number;
    [property: string]: any;
}

/**
 * Per-symbol cluster assignment produced by L1/S2.
 *
 * Clusters are scoped to one repo at a time — ``cluster_id`` is only
 * meaningful within ``repo``. The intent is "modules-as-emergent": a
 * sub-system that the symbol's structural neighbors form, regardless
 * of declared package boundaries.
 */
export interface SpectralClusterRow {
    cluster_id:      number;
    cluster_size:    number;
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * One symbol's membership in a subsystem (subsystem-extraction §2.4).
 *
 * One row per ``(subsystem_id, symbol_id)``. ``boundary_confidence`` ∈ [0,1]
 * is how strongly the symbol belongs to its subsystem: the mean co-association
 * (across the resolution sweep) with the other members of its assigned
 * subsystem. 1.0 = interior; low = a boundary/judgment-call assignment a
 * re-implementer must scrutinise. ``placement`` records whether the assignment
 * came from structure (``"structural"`` — the symbol carries typed-edge
 * signal) or from file locality (``"locality"`` — a zero-profile symbol placed
 * by its CONTAINS/directory home, per §2.3, because structure could not place
 * it).
 */
export interface SubsystemMemberRow {
    boundary_confidence: number;
    placement:           Placement;
    qualified_name:      string;
    repo:                string;
    schema_version?:     number;
    subsystem_id:        string;
    symbol_id:           string;
    [property: string]: any;
}

export type Placement = "structural" | "locality";

/**
 * One extracted subsystem — a full subcategory on a disjoint object set.
 *
 * Produced by ``ctkr subsystems`` (subsystem-extraction §2, Stage A —
 * DECOMPOSE). One row per ``(run_config, subsystem_id)``. The partition is a
 * consensus over a Louvain resolution sweep: ``persistence_score`` is the mean
 * pairwise co-association of the subsystem's members across the sweep (1.0 =
 * the members always co-cluster; low = a fragile grouping). ``config`` is the
 * JSON blob of the partition parameters + runtime metadata so a re-cut is
 * reproducible and the subsystem_id is verifiable.
 */
export interface SubsystemRow {
    config:            string;
    generated_at:      string;
    n_members:         number;
    persistence_score: number;
    repo:              string;
    resolution:        number;
    schema_version?:   number;
    subsystem_id:      string;
    [property: string]: any;
}

/**
 * One pairwise topological-distance entry between two repos.
 *
 * Produced by ``ctkr shape`` (L1/S1) alongside ``shape_pds.parquet``.
 * Despite the file name, the underlying metric is the **bottleneck
 * distance** (L∞-Wasserstein) between H₁ persistence diagrams —
 * chosen over full p-Wasserstein because it ships with the lighter
 * ``topo`` extra (gudhi, no ``pot`` dependency). The file name is
 * retained for historical / external-caller compatibility.
 *
 * Stored upper-triangle only (``repo_a < repo_b`` lexicographically);
 * the metric is symmetric, so the lower triangle is implied.
 */
export interface WassersteinH1Row {
    distance:        number;
    repo_a:          string;
    repo_b:          string;
    schema_version?: number;
    [property: string]: any;
}

