/**
 * AUTO-GENERATED — do not edit by hand.
 * Generated by: bun run codegen:ctkr-types
 * Source of truth: ctkr/ctkr/schema.py + ctkr/ctkr/schema_l3.py
 *
 * To regenerate:
 *   bun run codegen:ctkr-types
 *
 * To check for drift against hand-written types.ts:
 *   bun run codegen:check
 */

/**
 * Top-level pointer file for the ``.metacoding/ctkr/`` directory.
 *
 * Lives at ``.metacoding/ctkr/manifest.json``. Records which artifacts
 * are present, when they were generated, and what version of this
 * schema they were validated against. Cheap to read; tooling should
 * consult it before assuming an artifact exists.
 */
export interface ArtifactManifest {
    centrality?:         boolean;
    embedding_dim?:      number | null;
    embeddings?:         boolean;
    functor_edges?:      boolean;
    functors?:           boolean;
    generated_at:        string;
    hom_profiles?:       boolean;
    kind_weights?:       { [key: string]: number } | null;
    metacoding_data_dir: string;
    motif_instances?:    boolean;
    motifs?:             boolean;
    n_functor_edges?:    number;
    n_functors?:         number;
    n_hom_profiles?:     number;
    n_motif_instances?:  number;
    n_motifs?:           number;
    n_symbols?:          number;
    nn_index?:           boolean;
    notes?:              null | string;
    profile_depth?:      number | null;
    profile_vec_dim?:    number | null;
    schema_version?:     number;
    shape_pds?:          boolean;
    spectral_clusters?:  boolean;
    wasserstein_h1?:     boolean;
    [property: string]: any;
}

/**
 * Per-symbol centrality scores produced by L1/S2.
 *
 * All three measures are normalized to [0, 1] within the source graph.
 * ``betweenness`` is approximate when computed with sampling
 * (``k < |N|``) — recorded as the same column for consistency, with
 * the sampling factor noted in :attr:`ArtifactManifest.notes`.
 */
export interface CentralityRow {
    betweenness:     number;
    eigenvector:     number;
    pagerank:        number;
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * One symbol's embedding vector.
 *
 * Produced by L1/C1 (node2vec / GraphSAGE). All vectors in a single
 * ``embeddings.parquet`` MUST share a dimension; that dimension is
 * recorded in ``ArtifactManifest.embedding_dim``.
 */
export interface EmbeddingRow {
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    vec:             number[];
    [property: string]: any;
}

/**
 * One snippet of source evidence for a labeled pattern.
 *
 * Multiple rows per ``pattern_id``: each row points to a concrete
 * location in some repo whose code instantiates the pattern. The
 * snippet itself is materialized so the JSONL is self-contained for
 * review — no re-resolution needed against the indexed sources.
 */
export interface EvidenceRow {
    /**
     * Optional surrounding-symbol qualified_name (e.g. the enclosing class or function). Lets
     * reviewers orient without opening the file.
     */
    context?:        null | string;
    file:            string;
    line_range:      LineRangeObject;
    pattern_id:      string;
    repo:            string;
    schema_version?: number;
    snippet:         string;
    [property: string]: any;
}

/**
 * Inclusive line span in a source file.
 */
export interface LineRangeObject {
    end:   number;
    start: number;
    [property: string]: any;
}

/**
 * One object↦object correspondence — a weighted meta-graph edge (Phase 2c).
 *
 * Produced alongside ``FunctorRow`` by the functor-discovery runner. This is
 * the Phase 2c meta-graph edge stream (MetaCoding-at0): Louvain's nodes are
 * ``(repo, symbol_id)`` across the corpus and each row here is one weighted
 * meta-edge. ``functor_id`` is the FK back into ``functors.parquet``.
 *
 * Null semantics: ``pair_fidelity`` is ``-1`` when the source has no internal
 * incident edges (no structural evidence — consumers must NOT read this as
 * 1.0). ``margin`` is the σ gap to the best unaccepted alternative for this
 * source; low margin = the assignment was a near-coin-flip among lookalikes
 * (expected often under BORDERLINE seeds).
 */
export interface FunctorEdgeRow {
    dst_qualified_name: string;
    dst_repo:           string;
    dst_symbol_id:      string;
    functor_id:         string;
    margin:             number;
    n_edges_incident:   number;
    n_edges_preserved:  number;
    pair_fidelity:      number;
    schema_version?:    number;
    similarity:         number;
    src_qualified_name: string;
    src_repo:           string;
    src_symbol_id:      string;
    [property: string]: any;
}

/**
 * One discovered (approximate) functor ``F : C_src → C_dst`` — Phase 2b.
 *
 * Produced by the TS functor-discovery runner (``src/ctkr/functorRunner.ts``,
 * MetaCoding §6 Task 3). One row per ``(repo_src, repo_dst, config)`` — a
 * *directed* pair, so both directions of a repo pair appear as separate rows.
 * Python never writes these (TS owns Phase 2 per MetaCoding-p4b); this model
 * is the canonical schema authority so the codegen'd TS mirror and any
 * Python-side L3/analysis readers agree on shape and column order.
 *
 * Null semantics (§1.3): metrics with no evidence are stored as the sentinel
 * ``-1.0`` (a real float on disk — Parquet floats are not nullable in the
 * ``-1`` convention this artifact set uses) and surfaced as ``null`` by
 * consumers. ``fidelity`` is ``-1`` when ``n_edges_internal == 0`` (an
 * edgeless domain preserves nothing and proves nothing — it must fail any
 * ``min_fidelity > 0`` filter, NOT read as perfect 1.0). ``path_fidelity_2``
 * is ``-1`` when the 2-path composition diagnostic was not computed.
 * ``cycle_consistency`` is ``-1`` when the reverse-direction functor was not
 * computed under the same config.
 */
export interface FunctorRow {
    config:            string;
    coverage:          number;
    cycle_consistency: number;
    fidelity:          number;
    functor_id:        string;
    generated_at:      string;
    n_edges_internal:  number;
    n_edges_preserved: number;
    n_mapped:          number;
    n_objects_src:     number;
    path_fidelity_2:   number;
    repo_dst:          string;
    repo_src:          string;
    schema_version?:   number;
    [property: string]: any;
}

/**
 * One symbol's hom-profile — raw integer edge counts by (kind, direction).
 *
 * Produced by L1 (``ctkr hom-profiles``, MetaCoding-23q.1). The vector
 * is stored at **maximal precision** as unsigned integer counts (no
 * L1-normalisation, no quantisation, no kinds_filter baked into the
 * numbers). Per ``docs/notes/entropy-as-dial.md`` granularity is a
 * caller-tunable knob, so downstream tools re-normalise / discretize
 * at query time rather than the writer baking a choice into the bytes.
 *
 * Vector dimension is ``2 * len(EDGE_KINDS)`` from
 * ``ctkr.graph_loader.EDGE_KINDS`` (currently 28). Ordering convention:
 * for each ``ek in EDGE_KINDS``, the ``(ek, "in")`` slot precedes the
 * ``(ek, "out")`` slot. The canonical ``_DIMS`` list in
 * ``ctkr.hom_profiles`` is the single source of truth for the order.
 */
export interface HomProfileRow {
    profile_vec:     number[];
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * Inclusive line span in a source file.
 */
export interface LineRange {
    end:   number;
    start: number;
    [property: string]: any;
}

/**
 * One concrete occurrence of a motif in the corpus.
 *
 * Multiple rows per ``motif_id``; links back to the originating
 * symbol(s) so an evidence-fetcher (L3/F3) can pull snippets.
 */
export interface MotifInstanceRow {
    file:            string;
    line:            number;
    motif_id:        string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * One frequent typed subgraph discovered by L1/C2.
 *
 * ``signature`` is the canonical serialization of the motif's graph
 * structure (a typed-edge-list string, deterministic across runs of
 * the miner). It is the join key into ``motif_instances.parquet``.
 */
export interface MotifRow {
    edge_kinds:      EdgeKind[];
    motif_id:        string;
    repo_coverage:   string[];
    schema_version?: number;
    signature:       string;
    size_edges:      number;
    size_nodes:      number;
    support:         number;
    [property: string]: any;
}

export type EdgeKind = "CALLS" | "REFERENCES" | "EXTENDS" | "IMPLEMENTS" | "OVERRIDES" | "INJECTS" | "CONTAINS" | "IMPORTS" | "ANNOTATES" | "TYPE_OF";

/**
 * Metadata sidecar for the opaque ``nn_index/`` directory.
 *
 * The binary index itself (FAISS or hnswlib) is not a parquet table.
 * This sidecar records what's inside so callers don't have to
 * introspect the binary.
 */
export interface NNIndexMeta {
    backend:       Backend;
    built_at:      string;
    embedding_dim: number;
    /**
     * Relative path to the embeddings.parquet this index was built from. Used to detect
     * staleness when embeddings are regenerated.
     */
    embeddings_source: string;
    metric:            Metric;
    n_symbols:         number;
    schema_version?:   number;
    [property: string]: any;
}

export type Backend = "faiss" | "hnswlib";

export type Metric = "cosine" | "l2" | "ip";

/**
 * One labeled structural element produced by an L3 labeler.
 *
 * ``source_ref`` is a foreign key into the L1 artifact named by
 * ``source_kind``:
 *
 * - ``source_kind == "motif"``       → ``source_ref`` is a ``motif_id``
 * - ``source_kind == "role-cluster"`` → ``source_ref`` is a cluster id
 * - ``source_kind == "analogy"``      → ``source_ref`` is an analogy-pair id
 *
 * ``instances`` lists the concrete symbol_ids that participate; for
 * motifs these are the anchor symbols (matching
 * ``MotifInstanceRow.symbol_id`` in schema.py). The corresponding
 * code-evidence snippets live in ``evidence.jsonl``.
 *
 * Mandatory provenance fields — ``llm_model``, ``llm_temperature``,
 * ``prompt_version``, ``schema_version`` — make every label
 * invalidatable on prompt or model changes without re-running L1.
 */
export interface PatternRow {
    /**
     * LLM-reported or post-hoc confidence in [0, 1].
     */
    confidence: number;
    /**
     * One-paragraph explanation of what the pattern does and why it recurs.
     */
    description: string;
    /**
     * Optional explicit list of evidence row keys (pattern_id is the primary join; this field
     * is for cases where evidence rows are themselves uniquely keyed). May be empty if the join
     * is purely by pattern_id.
     */
    evidence_ids?: string[];
    generated_at:  string;
    /**
     * Symbol IDs (anchor symbols) participating in this pattern.
     */
    instances: string[];
    /**
     * Short canonical name (~3 words). Reused as a pattern key in downstream
     * cross-instantiation synthesis.
     */
    label:           string;
    llm_model:       string;
    llm_temperature: number;
    pattern_id:      string;
    prompt_version:  string;
    schema_version?: number;
    source_kind:     SourceKind;
    source_ref:      string;
    [property: string]: any;
}

export type SourceKind = "motif" | "role-cluster" | "analogy";

/**
 * Persistent-homology shape signature for one (repo, homology-dim) pair.
 *
 * Produced by L1/S1. ``persistence_pairs`` is encoded as flat parallel
 * lists rather than a list-of-tuples because Parquet's list<list<...>>
 * support varies across readers.
 */
export interface ShapePDRow {
    birth:           number[];
    death:           number[];
    dim:             number;
    repo:            string;
    schema_version?: number;
    [property: string]: any;
}

/**
 * Per-symbol cluster assignment produced by L1/S2.
 *
 * Clusters are scoped to one repo at a time — ``cluster_id`` is only
 * meaningful within ``repo``. The intent is "modules-as-emergent": a
 * sub-system that the symbol's structural neighbors form, regardless
 * of declared package boundaries.
 */
export interface SpectralClusterRow {
    cluster_id:      number;
    cluster_size:    number;
    qualified_name:  string;
    repo:            string;
    schema_version?: number;
    symbol_id:       string;
    [property: string]: any;
}

/**
 * One pairwise topological-distance entry between two repos.
 *
 * Produced by ``ctkr shape`` (L1/S1) alongside ``shape_pds.parquet``.
 * Despite the file name, the underlying metric is the **bottleneck
 * distance** (L∞-Wasserstein) between H₁ persistence diagrams —
 * chosen over full p-Wasserstein because it ships with the lighter
 * ``topo`` extra (gudhi, no ``pot`` dependency). The file name is
 * retained for historical / external-caller compatibility.
 *
 * Stored upper-triangle only (``repo_a < repo_b`` lexicographically);
 * the metric is symmetric, so the lower triangle is implied.
 */
export interface WassersteinH1Row {
    distance:        number;
    repo_a:          string;
    repo_b:          string;
    schema_version?: number;
    [property: string]: any;
}

