/**
 * codegen-ctkr-types.ts
 *
 * Step 1: Runs ctkr/scripts/emit_json_schema.py to produce per-model JSON
 *         Schema files under .metacoding/ctkr/schemas/.
 * Step 2: Feeds each JSON Schema into quicktype-core and merges the output
 *         into a single src/ctkr/types.gen.ts file.
 * Step 3: Structurally diffs types.gen.ts against the hand-written types.ts
 *         and reports missing/extra fields and type mismatches.
 *
 * Run with:
 *   bun run codegen:ctkr-types
 */

import { file, write } from "bun";
import path from "node:path";
import fs from "node:fs";
import {
  InputData,
  JSONSchemaInput,
  quicktype,
  FetchingJSONSchemaStore,
} from "quicktype-core";

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------
const REPO_ROOT = path.resolve(import.meta.dir, "..");
const SCHEMAS_DIR = path.join(REPO_ROOT, ".metacoding", "ctkr", "schemas");
const OUT_FILE = path.join(REPO_ROOT, "src", "ctkr", "types.gen.ts");
const HAND_WRITTEN = path.join(REPO_ROOT, "src", "ctkr", "types.ts");
const EMIT_SCRIPT = path.join(
  REPO_ROOT,
  "ctkr",
  "scripts",
  "emit_json_schema.py"
);

// ---------------------------------------------------------------------------
// Step 1: emit JSON schemas via Python
// ---------------------------------------------------------------------------
console.log("=== Step 1: emitting JSON schemas from pydantic models ===");
// Capture both streams and inspect the exit code rather than swallowing
// stderr: a non-zero `uv` exit (missing pydantic, an import error in
// schema.py, a broken venv) must fail this script loudly with the underlying
// diagnostics, not silently emit zero schemas downstream. `.nothrow()` lets us
// surface uv's stderr ourselves instead of a generic ShellError stack.
const emitResult = await Bun.$`uv run python ${EMIT_SCRIPT} --out-dir ${SCHEMAS_DIR}`
  .cwd(path.join(REPO_ROOT, "ctkr"))
  .nothrow()
  .quiet();
process.stdout.write(emitResult.stdout.toString());
if (emitResult.exitCode !== 0) {
  process.stderr.write(emitResult.stderr.toString());
  throw new Error(
    `Step 1 failed: \`uv run python emit_json_schema.py\` exited with code ${emitResult.exitCode}. ` +
      `See the uv/Python stderr above.`,
  );
}

// ---------------------------------------------------------------------------
// Step 2: run quicktype over each schema
// ---------------------------------------------------------------------------
console.log("\n=== Step 2: generating TypeScript types via quicktype-core ===");

const schemaFiles = fs
  .readdirSync(SCHEMAS_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

if (schemaFiles.length === 0) {
  throw new Error(`No JSON schemas found in ${SCHEMAS_DIR}`);
}

const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());

for (const schemaFile of schemaFiles) {
  const modelName = path.basename(schemaFile, ".json");
  const schemaContent = await file(path.join(SCHEMAS_DIR, schemaFile)).text();
  await schemaInput.addSource({
    name: modelName,
    schema: schemaContent,
  });
}

const inputData = new InputData();
inputData.addInput(schemaInput);

const result = await quicktype({
  inputData,
  lang: "typescript",
  rendererOptions: {
    // Keep snake_case field names to match the Python source of truth
    // (pydantic snake_case → no renaming)
    "just-types": "true",
    "prefer-unions": "true",
    "prefer-const-values": "false",
    "explicit-unions": "false",
  },
  inferMaps: false,
  inferEnums: true,
  inferDateTimes: false,
  inferUuids: false,
  inferIntegerStrings: false,
  inferBooleanStrings: false,
});

const banner = `/**
 * AUTO-GENERATED — do not edit by hand.
 * Generated by: bun run codegen:ctkr-types
 * Source of truth: ctkr/ctkr/schema.py + ctkr/ctkr/schema_l3.py
 *
 * To regenerate:
 *   bun run codegen:ctkr-types
 *
 * To check for drift against hand-written types.ts:
 *   bun run codegen:check
 */

`;

const genLines = result.lines.join("\n");
const fullOutput = banner + genLines + "\n";

await write(OUT_FILE, fullOutput);
console.log(`  wrote ${path.relative(REPO_ROOT, OUT_FILE)}`);

// ---------------------------------------------------------------------------
// Step 3: structural diff vs hand-written types.ts
// ---------------------------------------------------------------------------
console.log("\n=== Step 3: structural diff vs hand-written types.ts ===");

function extractInterfaces(src: string): Map<string, Set<string>> {
  /**
   * Very light parser: extract interface Name { field: type; ... } blocks.
   * Returns Map<InterfaceName, Set<"fieldName: normalised-type">>.
   * Not a full TS parser — handles the flat structures we have here.
   * Tolerates both 2-space (hand-written) and 4-space (quicktype) indentation.
   */
  const result = new Map<string, Set<string>>();
  // Match: export interface Foo { ... } (single-level, non-nested bodies)
  const ifaceRe = /export\s+interface\s+(\w+)\s*\{([^}]*)\}/gs;
  for (const match of src.matchAll(ifaceRe)) {
    const name = match[1]!;
    const body = match[2]!;
    const fields = new Set<string>();
    // Match "  fieldName?: SomeType;" or "    fieldName: SomeType;" (any indent)
    // Skip index signatures like [property: string]: any
    const fieldRe = /^\s+(\w+)\??\s*:\s*(.+?);/gm;
    for (const fm of body.matchAll(fieldRe)) {
      const fieldName = fm[1]!;
      const fieldType = fm[2]!.trim().replace(/\s+/g, " ");
      fields.add(`${fieldName}: ${fieldType}`);
    }
    if (fields.size > 0) {
      result.set(name, fields);
    }
  }
  return result;
}

const handSrc = await file(HAND_WRITTEN).text();
const genSrc = await file(OUT_FILE).text();

const handIfaces = extractInterfaces(handSrc);
const genIfaces = extractInterfaces(genSrc);

const handNames = new Set(handIfaces.keys());
const genNames = new Set(genIfaces.keys());

const missingInGen = [...handNames].filter((n) => !genNames.has(n));
const extraInGen = [...genNames].filter((n) => !handNames.has(n));
const inBoth = [...handNames].filter((n) => genNames.has(n));

let driftFound = false;

if (missingInGen.length > 0) {
  console.log("\n  MISSING in generated (present in hand-written):");
  for (const n of missingInGen) {
    console.log(`    - ${n}`);
  }
  driftFound = true;
}

if (extraInGen.length > 0) {
  console.log("\n  EXTRA in generated (not in hand-written):");
  for (const n of extraInGen) {
    console.log(`    + ${n}`);
  }
  driftFound = true;
}

if (inBoth.length > 0) {
  for (const name of inBoth) {
    const handFields = handIfaces.get(name)!;
    const genFields = genIfaces.get(name)!;
    const missingFields = [...handFields].filter((f) => !genFields.has(f));
    const extraFields = [...genFields].filter((f) => !handFields.has(f));
    if (missingFields.length > 0 || extraFields.length > 0) {
      console.log(`\n  ${name}:`);
      for (const f of missingFields) {
        console.log(`    - ${f}  (in hand-written, missing from generated)`);
      }
      for (const f of extraFields) {
        console.log(`    + ${f}  (in generated, not in hand-written)`);
      }
      driftFound = true;
    }
  }
}

if (!driftFound) {
  console.log("  No structural drift detected — hand-written and generated match.");
} else {
  console.log(
    "\n  NOTE: Some differences are expected (e.g. EdgeKind imported from" +
      " store/types.ts in hand-written vs inlined union in generated)."
  );
}

console.log("\n=== Codegen complete ===");
